#!/bin/sh
# properties = {"type": "single", "rule": "concat_and_sort_genotype_vcf", "local": false, "input": ["../../data/all_pools/chr1/all_pools.genotype.vcf.gz", "../../data/all_pools/chr2/all_pools.genotype.vcf.gz", "../../data/all_pools/chr3/all_pools.genotype.vcf.gz", "../../data/all_pools/chr4/all_pools.genotype.vcf.gz", "../../data/all_pools/chr5/all_pools.genotype.vcf.gz", "../../data/all_pools/chr6/all_pools.genotype.vcf.gz", "../../data/all_pools/chr7/all_pools.genotype.vcf.gz", "../../data/all_pools/chr8/all_pools.genotype.vcf.gz", "../../data/all_pools/chr9/all_pools.genotype.vcf.gz", "../../data/all_pools/chr10/all_pools.genotype.vcf.gz", "../../data/all_pools/chr11/all_pools.genotype.vcf.gz", "../../data/all_pools/chr12/all_pools.genotype.vcf.gz", "../../data/all_pools/chr13/all_pools.genotype.vcf.gz", "../../data/all_pools/chr14/all_pools.genotype.vcf.gz", "../../data/all_pools/chr15/all_pools.genotype.vcf.gz", "../../data/all_pools/chr16/all_pools.genotype.vcf.gz", "../../data/all_pools/chr17/all_pools.genotype.vcf.gz", "../../data/all_pools/chr18/all_pools.genotype.vcf.gz", "../../data/all_pools/chr19/all_pools.genotype.vcf.gz", "../../data/all_pools/chr20/all_pools.genotype.vcf.gz", "../../data/all_pools/chr21/all_pools.genotype.vcf.gz", "../../data/all_pools/chr22/all_pools.genotype.vcf.gz"], "output": ["../../data/all_pools/all_pools.genotype.MAF01.vcf.gz"], "wildcards": {"pool": "all_pools"}, "params": {"group": "-G teamtrynka", "queue": "-q normal", "threads": "-n 32", "memory": "-M250000 -R'span[hosts=1] select[mem>250000] rusage[mem=250000]'", "MAF": 0.01, "jobname": "-o ../../logs/log_all_pools_concat_and_sort_genotype_vcf.%J.%I", "error": "-e ../../errors/error_all_pools_concat_and_sort_genotype_vcf.%J.%I"}, "log": [], "threads": 1, "resources": {}, "jobid": 2, "cluster": {}}
cd /lustre/scratch123/hgi/mdt1/projects/otar2065/hipsci_genotype_processing/code/for_eQTL && \
/software/teamtrynka/conda/trynka-base/bin/python \
-m snakemake ../../data/all_pools/all_pools.genotype.MAF01.vcf.gz --snakefile /lustre/scratch123/hgi/mdt1/projects/otar2065/hipsci_genotype_processing/code/for_eQTL/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /lustre/scratch123/hgi/mdt1/projects/otar2065/hipsci_genotype_processing/code/for_eQTL/.snakemake/tmp.ttwjlmfc ../../data/all_pools/chr1/all_pools.genotype.vcf.gz ../../data/all_pools/chr2/all_pools.genotype.vcf.gz ../../data/all_pools/chr3/all_pools.genotype.vcf.gz ../../data/all_pools/chr4/all_pools.genotype.vcf.gz ../../data/all_pools/chr5/all_pools.genotype.vcf.gz ../../data/all_pools/chr6/all_pools.genotype.vcf.gz ../../data/all_pools/chr7/all_pools.genotype.vcf.gz ../../data/all_pools/chr8/all_pools.genotype.vcf.gz ../../data/all_pools/chr9/all_pools.genotype.vcf.gz ../../data/all_pools/chr10/all_pools.genotype.vcf.gz ../../data/all_pools/chr11/all_pools.genotype.vcf.gz ../../data/all_pools/chr12/all_pools.genotype.vcf.gz ../../data/all_pools/chr13/all_pools.genotype.vcf.gz ../../data/all_pools/chr14/all_pools.genotype.vcf.gz ../../data/all_pools/chr15/all_pools.genotype.vcf.gz ../../data/all_pools/chr16/all_pools.genotype.vcf.gz ../../data/all_pools/chr17/all_pools.genotype.vcf.gz ../../data/all_pools/chr18/all_pools.genotype.vcf.gz ../../data/all_pools/chr19/all_pools.genotype.vcf.gz ../../data/all_pools/chr20/all_pools.genotype.vcf.gz ../../data/all_pools/chr21/all_pools.genotype.vcf.gz ../../data/all_pools/chr22/all_pools.genotype.vcf.gz --latency-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules concat_and_sort_genotype_vcf --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch "/lustre/scratch123/hgi/mdt1/projects/otar2065/hipsci_genotype_processing/code/for_eQTL/.snakemake/tmp.ttwjlmfc/2.jobfinished" || (touch "/lustre/scratch123/hgi/mdt1/projects/otar2065/hipsci_genotype_processing/code/for_eQTL/.snakemake/tmp.ttwjlmfc/2.jobfailed"; exit 1)

