---

############################################################################################################################
#################################################### INFORMATION ###########################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN COMMON VARIABLES ##########################################################
############################################################################################################################

# Folder where all the outputs are saved (LD scores, prioritization results files, etc.) 
# CELLECT-LDSC and CELLECT-MAGMA will write the analysis results into <BASE_OUTPUT_DIR>/CELLECT-LDSC and <BASE_OUTPUT_DIR>/CELLECT-MAGMA subdirectories respectively. The directory and its subdirectories will be created if they do not exist.
BASE_OUTPUT_DIR: ../../../data/results/CELLECT


### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
# the files can be uncompressed or compressed (gz/bz2 formats are supported).
SPECIFICITY_INPUT:
  - id: microglia-cellex
    path: ../../../data/results/CELLECT/cellex_treatment.csv.gz # 3 annotations
  - id: microglia-treatment-DEG-logfc
    path: ../../../data/results/CELLECT/treatments_DEG_normalised_logFC.csv.gz # 6 annotations
  - id: microglia-treatment-DEG-t
    path: ../../../data/results/CELLECT/treatments_DEG_normalised_t.csv.gz # 6 annotations
  - id: microglia-PRS-DEG-logfc
    path: ../../../data/results/CELLECT/PRS_DEG_normalised_logFC.csv.gz # 6 annotations
  - id: microglia-PRS-DEG-t
    path: ../../../data/results/CELLECT/PRS_DEG_normalised_t.csv.gz # 6 annotations
  - id: microglia-APOE-DEG-logfc
    path: ../../../data/results/CELLECT/APOE_DEG_normalised_logFC.csv.gz # 6 annotations
  - id: microglia-APOE-DEG-t
    path: ../../../data/results/CELLECT/APOE_DEG_normalised_t.csv.gz
### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats. Uncompressed / gz or bz2 compressed files allowed.
GWAS_SUMSTATS:
  - id: AD_Bellenguez
    path: ../../../data/results/CELLECT/GCST90027158.sumstats.gz
  - id: AD_Schwartzentruber
    path: ../../../data/results/CELLECT/GCST90012877.sumstats.gz
  - id: PD_Nalls
    path: ../../../data/results/CELLECT/ieu-b-7_PD_Nalls_2019.sumstats.gz
  - id: ALS_van_Rheenen
    path: ../../../data/results/CELLECT/GCST90027163.sumstats.gz
  - id: LBD_Chia
    path: ../../../data/results/CELLECT/GCST90001390.sumstats.gz
  - id: Height_Yengo
    path: ../../../data/results/CELLECT/GCST006901.sumstats.gz

ANALYSIS_TYPE: # specify what analysis type to run. At least one analysis type needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: False # performs conditional analysis for selected annotations.
  heritability: True # [CELLECT-LDSC ONLY] estimates heritability for selected annotations. 
  heritability_intervals: False # [CELLECT-LDSC ONLY] estimates heritability intervals for selected annotations. 'heritability' must be True when enabling heritability_intervals

WINDOW_DEFINITION: # Window definition for mapping gene specificity values to SNPs
  WINDOW_SIZE_KB:
    100

GENE_COORD_FILE: # Path to gene coordinates. First five columns must be: ensembl_gene_id, chromosome, start_position, stop_position, strand. No header allowed
  ../../../data/results/CELLECT/data_for_cellect/gene_annotations/gene_coordinates.GRCh37.ensembl_v91.txt
KEEP_ANNOTS: # [CELLECT-LDSC ONLY] If True, for each specificity input a file containing the SNP:ES (and all overlapping genes) mappings will be saved to output also. 
#If you only want this and do not wish to run the rest of CELLECT add "--until make_annot" to the normal snakemake command
  True

############################################################################################################################
############################################## CONDITIONAL ANALYSIS ########################################################
############################################################################################################################

### CONDITIONAL_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to condition on
# NOTE: you can delete or leave these dicts blank if the 'analysis type' is not activated
CONDITIONAL_INPUT:
#  - id: microglia-treatment
#    annotations: ['ABC']
  # - id: tabula_muris-test
  #   annotations: ['XX']


############################################################################################################################
###################################### HERITABILITY ANALYSIS (LDSC ONLY) ###################################################
############################################################################################################################

### HERITABILITY_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to estimate heritability for
# NOTE: you can delete or leave these dicts blank if the 'analysis type' is not activated
HERITABILITY_INPUT:
  - id: microglia-cellex
    annotations: ['untreated','IFN','LPS']
  - id: microglia-PRS-DEG-logfc
    annotations: ["untreated_higher_high_PRS", "untreated_higher_low_PRS","IFN_higher_low_PRS" , "IFN_higher_high_PRS", "LPS_higher_high_PRS", "LPS_higher_low_PRS"]
############################################################################################################################
####################################### EFFECTOR GENE ANALYSIS (MAGMA ONLY) #################################################
############################################################################################################################
# NOTE: you can delete or leave these dicts blank or as they are if the effector_genes analysis type is not activated
N_GENES_MAGMA: 1000 # number of top magma genes to include, sorted by p-value in ascending order
PERCENTILE_CUTOFF_ESMU: 90 # percentile cutoff for non-zero ESmu genes to include, sorted by ESmu value in descending order

#############################################################################################################################
##################################################### CONSTANTS #############################################################
#############################################################################################################################

# You generally do not need to change these variables.

LDSC_CONST:
  DATA_DIR: # Path to the data used for CELLECT-LDSC (baseline model, gene mapping etc).
    ../../../data/results/CELLECT/data_for_cellect/
  LDSC_DIR: # Path to the a cloned version of the github repo pascaltimshel/ldsc. This is included as a git submodule.
    /software/team152/oa3/CELLECT/ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1


MAGMA_CONST:
  DATA_DIR: # Path to the data used for CELLECT-MAGMA (baseline model, gene mapping etc).
    ../../../data/results/CELLECT/data_for_cellect/
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via the '-j' flag.
    1
  EXCLUDE_MHC: # Exclude genes located in the MHC region (chr6:27Mb-32Mb) during prioritization. 
  # We recommend setting this to True, unless you know what you are doing and analysing immune GWAS traits.
  # CELLECT-LDSC also does not include genetic signal from the MHC region.
    True
